Milestone-1: Mobile version skeleton
AngomRanjan/Profile pull request #1
Opened 2022-04-22 01:32 UTC by AngomRanjan

## Profile Setup Milestone-1: Mobile version skeleton
- Setup HTML/CSS Linters for the Project
- Added Header (toolbar) Section 
- Added Headline Section

2022-04-22 02:03 UTC, melaniesigrid requested changes
Hi @AngomRanjan , 

GREAT job so far! 🥳 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ All linters are passing, your project is professional with a proper README.
✅ I was impressed by the look of your project! You made the design look INCREDIBLE ✨ 
✅ Your project is one of the best I have seen.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 02:03 UTC, melaniesigrid commented on index.html
> +    </header>
## Changes required!

⚠️ The requirements state that "The logo (if the design has one) is on the left and has a link (a tag)". Currently, you have a logo. However, it's just a div with plain text. Make it a link with an `<a>` tag!

2022-04-22 02:03 UTC, melaniesigrid commented on index.html
> +    </div>
## Changes Required!

⚠️ According to the project requirements, "the headline section is a `section` tag".  Kindly correct it and change from a `<div>` to a `<section>`.  More info? https://www.w3schools.com/tags/tag_section.asp

2022-04-22 02:03 UTC, melaniesigrid commented on index.html
> +      <div class="container" id="toolbar">
## [OPTIONAL]

♻️ This is the mobile version of your application. You included a wrapper element with a set width to make it look like the mobile version, even when viewed on desktop.  You will keep building the application, and add styling to make it look proper on desktop in the future! Therefore, when developing for mobile, instead of adding a wrapper element, resize your own window's width.  You can also view it on different screen resolutions using Chrome Developer Tools.

Remove this container, to ensure that there is no "gray border". Don't worry about making it look good on a desktop yet. We are developing Mobile-First! 📱 

![image](https://user-images.githubusercontent.com/53036416/164581239-6aabf394-a4c8-4cca-9d4c-46a4b7e82220.png)

2022-04-22 05:06 UTC, AngomRanjan commented on index.html
> +    </header>
change made

2022-04-22 05:07 UTC, AngomRanjan commented on index.html
> +    </div>
change made

2022-04-22 05:21 UTC, phelian23 approved these changes
Hi @AngomRanjan, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 05:27 UTC, merged

2022-10-11 08:37 UTC, AngomRanjan commented
Hi Melanie,
Thank you very much for your review and suggestions.  It is very much
appreciated and I needed it.
I have made the first two changes. Can I keep the wrapper for time being as
the dateline for the week is near and I'm yet to start the next project?
Looking forward to hearing from you.
Angom

On Fri, Apr 22, 2022 at 7:33 AM Melanie Arellano ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @AngomRanjan <https://github.com/AngomRanjan> ,
>
> GREAT job so far! 🥳
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Highlights
>
> ✅ All linters are passing, your project is professional with a proper
> README.
> ✅ I was impressed by the look of your project! You made the design look
> INCREDIBLE ✨
> ✅ Your project is one of the best I have seen.
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/AngomRanjan/Profile/pull/1#discussion_r855706567>:
>
> > +    <header class="header">
>
> +      <div class="container" id="toolbar">
>
> +        <div class="logo" id="logo">
>
> +          <div class="logo-text">My Logo</div>
>
> +        </div>
>
> +        <div class="header-right">
>
> +          <img class="icons" id="menu" src="icons/union.png" alt="menu-icn">
>
> +        </div>
>
> +      </div>
>
> +    </header>
>
>
> Changes required!
>
> ⚠️ The requirements state that "The logo (if the design has one) is on
> the left and has a link (a tag)". Currently, you have a logo. However, it's
> just a div with plain text. Make it a link with an tag!
> ------------------------------
>
> In index.html
> <https://github.com/AngomRanjan/Profile/pull/1#discussion_r855707443>:
>
> > +    <div class="container" id="headline">
>
> +      <h1 class="head1" id="title">I’m Mariane Glad to see you!</h1>
>
> +      <p class="description" id="title-desc">I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded, don’t hestiate to contact me.</p>
>
> +      <h2 class="head2" id="headline2">LET’S CONNECT</h2>
>
> +      <ul class="connect-lists">
>
> +        <li class="connect-items" id="connect-item1"><a href="https://twitter.com/RanjanAngom"><img src="images/twitter.png" alt="twitter link"></a></li>
>
> +        <li class="connect-items" id="connect-item2"><a href="https://linkedin.com/in/angom-chittaranjan"><img src="images/linkedin.png" alt="linkedin link"></a></li>
>
> +        <li class="connect-items" id="connect-item3"><a href="https://medium.com/"><img src="images/medium.png" alt="medium link"></a></li>
>
> +        <li class="connect-items" id="connect-item4"><a href="https://github.com/AngomRanjan"><img src="images/github.png" alt="github link"></a></li>
>
> +        <li class="connect-items" id="connect-item5"><a href="https://angel.co/"><img src="images/angellist.png" alt="angellist link"></a></li>
>
> +      </ul>
>
> +    </div>
>
>
> Changes Required!
>
> ⚠️ According to the project requirements, "the headline section is a
> section tag". Kindly correct it and change from a
> to a . More info? https://www.w3schools.com/tags/tag_section.asp
>
> ------------------------------
>
> In index.html
> <https://github.com/AngomRanjan/Profile/pull/1#discussion_r855710511>:
>
> > +  </head>
>
> +<body>
>
> +  <div class="wrapper">
>
> +    <header class="header">
>
> +      <div class="container" id="toolbar">
>
>
> [OPTIONAL]
>
> ♻️ This is the mobile version of your application. You included a wrapper
> element with a set width to make it look like the mobile version, even when
> viewed on desktop. You will keep building the application, and add styling
> to make it look proper on desktop in the future! Therefore, when developing
> for mobile, instead of adding a wrapper element, resize your own window's
> width. You can also view it on different screen resolutions using Chrome
> Developer Tools.
>
> Remove this container, to ensure that there is no "gray border". Don't
> worry about making it look good on a desktop yet. We are developing
> Mobile-First! 📱
>
> [image: image]
> <https://user-images.githubusercontent.com/53036416/164581239-6aabf394-a4c8-4cca-9d4c-46a4b7e82220.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AngomRanjan/Profile/pull/1#pullrequestreview-949361833>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXWTX237B5GHCGGSX7LT5ODVGICGBANCNFSM5UA3YTYQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>